[theme]
base = "light"
primaryColor = "#f044b5"
backgroundColor = "#f7f6f4"
secondaryBackgroundColor = "#fffdfd"
textColor = "#282429"
font = "sans serif"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
